# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffee.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_roastType = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_roastType.setObjectName("comboBox_roastType")
        self.gridLayout.addWidget(self.comboBox_roastType, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_volume = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_volume.setMaximum(1000000000)
        self.spinBox_volume.setObjectName("spinBox_volume")
        self.gridLayout.addWidget(self.spinBox_volume, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboBox_millType = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_millType.setObjectName("comboBox_millType")
        self.gridLayout.addWidget(self.comboBox_millType, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_taste = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_taste.setObjectName("lineEdit_taste")
        self.gridLayout.addWidget(self.lineEdit_taste, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_title = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.gridLayout.addWidget(self.lineEdit_title, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.spinBox_cost = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_cost.setMaximum(1000000000)
        self.spinBox_cost.setObjectName("spinBox_cost")
        self.gridLayout.addWidget(self.spinBox_cost, 4, 1, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 6, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Тип кофе"))
        self.label_4.setText(_translate("Dialog", "Вкус"))
        self.label_2.setText(_translate("Dialog", "Степень обжарки"))
        self.label_6.setText(_translate("Dialog", "Объем"))
        self.label.setText(_translate("Dialog", "Название"))
        self.label_5.setText(_translate("Dialog", "Стоимость"))
        self.pushButton_save.setText(_translate("Dialog", "Сохранить"))
