# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showCoffee.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_showCoffee = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_showCoffee.setObjectName("pushButton_showCoffee")
        self.gridLayout.addWidget(self.pushButton_showCoffee, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.pushButton_addCoffee = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_addCoffee.setObjectName("pushButton_addCoffee")
        self.gridLayout.addWidget(self.pushButton_addCoffee, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_showCoffee.setText(_translate("Form", "Показать"))
        self.pushButton_addCoffee.setText(_translate("Form", "Добавить"))
